### PR TITLE
`ths` renamed to `thisArg` for clarity.

### PR DESCRIPTION
**Pull request by gmarceau**
@paulmelnikow @dlsmith

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Woot! :+1:

**Comment by dlsmith** [comment]
Is your intention to eventually merge this fork into the original repo? Maybe it makes sense to alias this instead for compatibility?

Also, can you update the README?

**Comment by gmarceau** [comment]
Yes, I'll open a PR on the original repo. If the new team isn't responsive to PR, I'll try to get us commit access. If all fail, running our own fork would be fine. There is no upstream development to speak of, outside of myself.

**Comment by dlsmith** [comment]
:+1:

**Comment by dlsmith** [comment]
Thanks @gmarceau

**Pull request merged**
